version: '3.9'

services:
  prisma:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14.2-alpine
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./local-services/postgres/data:/var/lib/postgresql/data
      - ./local-services/postgres/postgresql.conf:/psql.conf
    healthcheck:
      test: pg_isready -h localhost -d main
      timeout: 1s
      retries: 30
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: main
      PGDATA: /var/lib/postgresql/data/pgdata
